apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: es-http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: es-transport
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.211.55.25