apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - name: http
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.211.55.25


#  type: ClusterIP